apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: cgnet-exporter
  labels:
    app: cgnet-exporter
    k8s-app: cgnet-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: cgnet-exporter
  endpoints:
  - port: http-metrics
    interval: 30s
